### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/backgrounds/office_backgrounds/' 

### ISSUE THREAD

**Issue by scut-salmon** [chenmingxiang110/Chinese-automatic-speech-recognition#1]
Hi, I got this problem when running the code train901.py. Could you please offer this directory, or how can I generate it by myself? I think this is for argumentation maybe

**Comment by chenmingxiang110** [comment]
May I have your email pls?

**Comment by chenmingxiang110** [comment]
> Hi, I got this problem when running the code train901.py. Could you please offer this directory, or how can I generate it by myself? I think this is for argumentation maybe

May I have your email pls?

**Comment by nickluo1** [comment]
就用中文书写了，请问下仅用公开数据集怎么训练？需要修改哪些代码，谢谢
email jy03667148@163.com
