### ISSUE TITLE
YouTube上获取MP4

### ISSUE THREAD

**Issue by lawrence124** [chenmingxiang110/Chinese-automatic-speech-recognition#10]
从YouTube上获取MP4视频文件后转化成wav音频，同时使用对应的srt字幕文件作为target。总计时长大约120小时，有约20万条语音数据。数据量过大，且有版权归属问题，所以暂时不提供公开下载渠道。

--> 想知道你是怎么做到的？我想做类似的事情，去进行TTS培训

**Comment by chenmingxiang110** [comment]
谢谢你的提问，有很多youtube to MP3/MP4/wav/srt的网站，你可以试试看从那上面爬
