### ISSUE TITLE
谷歌拼音输入法，爬不了，帮解决一下呗

### ISSUE THREAD

**Issue by wyf19941128** [chenmingxiang110/Chinese-automatic-speech-recognition#3]

**Comment by chenmingxiang110** [comment]
谢谢你对项目的支持！我在实际使用的时候是根据场景语料自己写了一个输入法，但写得不太好，你可以参考下：https://github.com/chenmingxiang110/Android-pinyin-converter。

另外，想用谷歌API的话那只能找科学上网的办法了，我确实没有找到谷歌之外的拼音输入法api，很不好意思。

**Comment by wyf19941128** [comment]
> 谢谢你对项目的支持！我在实际使用的时候是根据场景语料自己写了一个输入法，但写得不太好，你可以参考下：[https://github.com/chenmingxiang110/Android-pinyin-converter。](https://github.com/chenmingxiang110/Android-pinyin-converter%E3%80%82)
> 
> 另外，想用谷歌API的话那只能找科学上网的办法了，我确实没有找到谷歌之外的拼音输入法api，很不好意思。

国内的谷歌翻译，也有这个功能，不过似乎需要调整，每次爬虫的url需要更改

**Comment by chenmingxiang110** [comment]
哦？请问能发我一下url吗？我push一下

> > 谢谢你对项目的支持！我在实际使用的时候是根据场景语料自己写了一个输入法，但写得不太好，你可以参考下：[https://github.com/chenmingxiang110/Android-pinyin-converter。](https://github.com/chenmingxiang110/Android-pinyin-converter%E3%80%82)
> > 另外，想用谷歌API的话那只能找科学上网的办法了，我确实没有找到谷歌之外的拼音输入法api，很不好意思。
> 
> 国内的谷歌翻译，也有这个功能，不过似乎需要调整，每次爬虫的url需要更改

哦？请问能发我一下api地址吗？我push一下

**Comment by wyf19941128** [comment]
> 哦？请问能发我一下url吗？我push一下
> 
> > > 谢谢你对项目的支持！我在实际使用的时候是根据场景语料自己写了一个输入法，但写得不太好，你可以参考下：[https://github.com/chenmingxiang110/Android-pinyin-converter。](https://github.com/chenmingxiang110/Android-pinyin-converter%E3%80%82)
> > > 另外，想用谷歌API的话那只能找科学上网的办法了，我确实没有找到谷歌之外的拼音输入法api，很不好意思。
> > 
> > 
> > 国内的谷歌翻译，也有这个功能，不过似乎需要调整，每次爬虫的url需要更改
> 
> 哦？请问能发我一下api地址吗？我push一下

"https://translate.google.cn/translate_a/single?client=webapp&sl=auto&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=sos&dt=ss&dt=t&source=bh&ssel=0&tsel=0&xid=45662847&kc=1&tk=644095.988078&q="+pinyin

**Comment by wyf19941128** [comment]
url这个你试试，谷歌的翻译器

**Comment by wyf19941128** [comment]
后边输出的分词需要改改

**Comment by chenmingxiang110** [comment]
> 后边输出的分词需要改改

OK，我已经搞好了，最近会合进来

**Comment by chenmingxiang110** [comment]
> 后边输出的分词需要改改

非常感激你提出来的建议。我准备close issue了，还有其他问题的话可以用我留在readme里的邮箱联系我，谢谢！
