### ISSUE TITLE
youtube data link 

### ISSUE THREAD

**Issue by ExpressGit** [chenmingxiang110/Chinese-automatic-speech-recognition#6]
hello @chenmingxiang110  can you provider youtube data link to email.
527190972@qq.com

**Comment by chenmingxiang110** [comment]
谢谢你对项目的关注，由于数据量过大，且有版权归属问题，所以暂时不提供对外的下载渠道。但我提供的模型是在全量数据的基础上训练的，你可以先使用看看。

MK tank <notifications@github.com> 于2020年7月8日周三 下午2:02写道：
