### ISSUE TITLE
关于模型大小问题

### ISSUE THREAD

**Issue by ENjoy924** [chenmingxiang110/Chinese-automatic-speech-recognition#7]
你好，下载 了你的model3模型，发现是1G多，而我自己训练出来的model3模型才300M，请问是什么原因

**Comment by chenmingxiang110** [comment]
这个我之前确实没有遇到过。请问你用的是train903和model903进行的训练吗？还是自己写了其他的脚本？

**Comment by ENjoy924** [comment]
是用train903和model903训练的，代码里用的是youtube数据集和aishell数据集，我把youtube数据集那块给删了，只剩下aishell数据集训练，保存保存下来的网络模型变成了300M

**Comment by chenmingxiang110** [comment]
我也问了一些朋友，都表示没有遇到过这个问题。我也很不解，很抱歉没法帮到你。不过issue我会继续保留，希望如果有其他人遇到相同问题的话能给予你解答。

**Comment by ENjoy924** [comment]
很感谢你的耐心解答，好像是代码没有下载完全导致的，感谢提供了这么好的开源项目

**Comment by chenmingxiang110** [comment]
谢谢你的支持，那既然问题已经找到了我就先关掉这个issue了，如果还有问题，欢迎联系我的邮箱。
