### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: /models/v903 : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3 ; No such process

### ISSUE THREAD

**Issue by reporter-law** [chenmingxiang110/Chinese-automatic-speech-recognition#9]
完整报错的地方
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "J:/PyCharm项目/项目/语音命令库/expand/Chinese-speech-recognition/user.py", line 38, in <module>
    saver.restore(sess, "/models/"+model_name+"/"+model_name+"_0.ckpt")
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\training\saver.py", line 1266, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\training\checkpoint_management.py", line 372, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 361, in get_matching_files
    return get_matching_files_v2(filename)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 389, in get_matching_files_v2
    for single_filename in pattern
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: /models/v903 : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process

**Comment by chenmingxiang110** [comment]
我自己不是windows，可能没办法完整复现你的这个错误。但我感觉是不是文件名或者路径错了呀？请问是否有下载model 903，并保存在 "/models/"+model_name+"/"+model_name+"_0.ckpt" 这个位置呢？

**Comment by chenmingxiang110** [comment]
> 完整报错的地方
> Instructions for updating:
> Use standard file APIs to check for files with this prefix.
> Traceback (most recent call last):
> File "J:/PyCharm项目/项目/语音命令库/expand/Chinese-speech-recognition/user.py", line 38, in
> saver.restore(sess, "/models/"+model_name+"/"+model_name+"_0.ckpt")
> File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\training\saver.py", line 1266, in restore
> if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
> File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
> return func(*args, **kwargs)
> File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\training\checkpoint_management.py", line 372, in checkpoint_exists
> if file_io.get_matching_files(pathname):
> File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 361, in get_matching_files
> return get_matching_files_v2(filename)
> File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 389, in get_matching_files_v2
> for single_filename in pattern
> File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: /models/v903 : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
> ; No such process

你好请问问题解决了吗

**Comment by reporter-law** [comment]
十分感谢您的解答，这个问题查了以下发现问题在这里，这个"/models/"+model_name+"/"+model_name+"_0.ckpt" 的"_0.ckpt"要改为"_1.ckpt"
但是还有一个问题就是谷歌仍要翻墙

**Comment by chenmingxiang110** [comment]
用谷歌翻译还是要翻墙吗？

**Comment by reporter-law** [comment]
> 用谷歌翻译还是要翻墙吗？

是的，谷歌翻译也要翻墙，否者用不了！！！

**Comment by chenmingxiang110** [comment]
> > 用谷歌翻译还是要翻墙吗？
> 
> 是的，谷歌翻译也要翻墙，否者用不了！！！

那要不然只能考虑自己收集一些语料写一个ngram吧，这个超出识别的范畴了

**Comment by chenmingxiang110** [comment]
如果没有其他问题的话我就关闭这个issue了，有其他问题的话可以重开一个issue或者直接联系我的邮箱:-)
